version: '3.8'

services:
  back:
      image: my-spring-boot-app
      ports: 
          - 9001:9000
      depends_on:
          - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RoadTrip
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "6000:6000"

volumes:
    sample_db: {}